# Generated by Django 5.2.4 on 2025-08-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
